config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users
  resources :users
  namespace :admin do 
    resources :projects, only: :index
  end
  
  resources :projects do
    resources :tasks do
      member do
        get :include
        get :exclude        
      end
    end
    collection do
      get :find
    end
    member do
      get :select_tasks
      get :all_tasks
      get :unassign_user
    end
  end
  
end

app/models/task.rb
class Task < ApplicationRecord
  has_closure_tree #order: 'sort_order'
  default_scope { order('sort_order') }
  
  enum state: [:excluded, :inprogress, :complete]
  
  belongs_to :project
  
  serialize :prereqs, Array
  
  def large_icon_path
    icon_path.gsub('/24/', '/48/').gsub('24.png', '48.png')
  end
  
  def template_file_url
    "/#{template_file_path}"
  end

  def template_file_path
    File.join("templates", "#{template_name}.xlsx")
  end
  
  def has_template_file?
    !self.template_name.blank? && File.exists?(Rails.root.join('public', template_file_path))
  end
  
  def has_template?
    !template_url.blank?
  end
  
  def has_downloadable_google_template?
    !google_template_download_url.blank?
  end
  
  def google_template_download_url
    if template_id
      "https://docs.google.com/spreadsheets/d/#{template_id}/export?format=xlsx"
    else
      nil
    end
  end
  
  def template_id
    if template_url.to_s =~ /id=(.+)$/
      $1
    else
      nil
    end
  end
  
  def prereq_tasks
    self.project.tasks.where(name: prereqs)
  end
  
  def incomplete_prereq_tasks
    @incomplete_prereq_tasks ||= prereq_tasks.where(state: [:inprogress, :excluded])
  end
  
  def excluded_prereq_tasks
    @excluded_prereq_tasks ||= prereq_tasks.where(state: :excluded)
  end
  
  def dependencies
    @dependencies ||= self.project.tasks.select {|t| t.prereqs.include? self.name }
  end
  def included_dependencies
    @included_dependencies ||= dependencies.select {|t| t.included? }
  end
  def complete_dependencies
    @complete_dependencies ||= included_dependencies.select {|t| t.complete? }
  end
  
  
  
  
  def download_status
    if excluded? 
      'excluded'
    elsif download_complete? || !download_location.blank?
      'complete'
    else
      'incomplete'
    end
  end
  
  def status
    if excluded?
      'excluded'
    elsif complete?
      'complete'
    else
      'inprogress'
    end
  end
  
  def status_label
    s = status
    s == 'inprogress' ? 'in progress' : s
  end
  
  def completable?
    self.included? && !self.children.any?
  end
  
  def includable?
    !children.any?
  end
  
  def included?
    !excluded?
  end
  
  def complete?
    if children.any?
      children.all? {|c| c.complete? || c.excluded? }
    else
      super
    end
  end
  
  def excluded?
    if children.any?
      children.all?(&:excluded?)
    else
      super
    end
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  def show
    @task = Task.find(params[:id])
    @project = @task.project
  end
  
  def update
    task = Task.find(params[:id])
    update_type = nil
    if params[:task]["task_#{task.id}_included"]=="1"
      update_type=:inclusion
      task.inprogress!
    elsif params[:task]["task_#{task.id}_included"]=="0"
      update_type=:inclusion
      task.excluded!
    elsif params[:task]["task_#{task.id}_complete"]=="1"
      update_type=:completion
      task.complete!
    elsif params[:task]["task_#{task.id}_complete"]=="0"
      update_type=:completion
      task.inprogress!
    else
      task.update_attributes!(task_params)
    end
    respond_to do |format|
      format.html { 
        @task = task
        redirect_back(fallback_location: project_path(@task.project))
      }
      format.js { 
        if update_type == :inclusion
          @task = task
          render 'include_task_checkbox'
        else
          set_task_and_project_from_parent
          if @task.is_a?(Project)
            render 'all_tasks'
          else
            render 'task_checkbox'
          end
        end
      }
    end
  end
  
  def include
    selected_task = Task.find(params[:id])
    selected_task.inprogress!
    set_task_and_project_from_parent
    respond_to do |format|
      format.js {
        if @task.is_a?(Project)
          render 'all_tasks'
        else
          render 'task_checkbox'
        end
      }
    end
  end
  def exclude
    selected_task = Task.find(params[:id])
    selected_task.excluded!
    set_task_and_project_from_parent
    respond_to do |format|
      format.js {
        if @task.is_a?(Project)
          render 'all_tasks'
        else
          render 'task_checkbox'
        end
      }
    end
  end
  
  private
  def set_task_and_project_from_parent
    @task = Task.find_by_id(params[:parent_task])
    if @task
      @project = @task.project
    else
      @project = Project.find_by_id(params[:parent_task])
      @task = @project
    end    
  end
  def task_params
    params.require(:task).permit(:download_location, :download_complete)
  end
  
end

app/views/tasks/_change_completion_script.html.haml
= "SingleSteps.changeCompletion(this, '#{j(task.name)}', '#{action}', event)"

app/views/tasks/_iconed_task.html.haml
- large = large || false
- if !task.icon_path.blank?
  %span.task-with-icon<
    %img.task-icon{src: large ? task.large_icon_path : task.icon_path}
    = task.name.strip
- else 
  = task.name

app/views/tasks/_include_task.html.haml
- skip_children ||= false
%li{class: "task task--#{task.status} #{task.children.any? ? 'task--group' : 'task--single'}", id: "task-#{task.id}"}
  - if !task.children.any?
    = render 'tasks/include_task_checkbox', task: task
  - else
    = link_to  project_task_path(task.project, task) do
      = render 'tasks/iconed_task', task: task
    - if !skip_children
      .task-list
        %ul
          - task.children.each do |sub_task|
            = render 'tasks/include_task', task: sub_task
    

app/views/tasks/_include_task_checkbox.html.haml
- label ||= nil
= form_for [task.project, task], :html=>{class: 'task__checkbox task__checkbox--labeled'}, remote: true, :authenticity_token => true do |f|
  = render 'tasks/incomplete_prereqs', task: task
  = f.check_box "task_#{task.id}_included", onclick: render('tasks/change_completion_script', task: task, action: (task.included? ? 'exclude' : 'include')), checked: task.included?
  - if label
    = f.label "task_#{task.id}_included", label
- if !label
  = link_to  project_task_path(task.project, task) do
    = render 'tasks/iconed_task', task: task

app/views/tasks/_incomplete_prereqs.html.haml
.excluded-prereqs{'data-count': task.excluded_prereq_tasks.count}
  %ul
    - task.excluded_prereq_tasks.each do |t|
      %li.incomplete-prereq{class: "task--#{t.status}"}
        = link_to t.name, project_task_path(t.project, t)
.incomplete-prereqs{'data-count': task.incomplete_prereq_tasks.count}
  %ul
    - task.incomplete_prereq_tasks.each do |t|
      %li.incomplete-prereq{class: "task--#{t.status}"}
        = link_to t.name, project_task_path(t.project, t)
        = t.excluded? ? '(not selected)' : '(incomplete)'
.complete-dependencies{'data-count': task.complete_dependencies.count}
  %ul
    - task.complete_dependencies.each do |t|
      %li.incomplete-prereq{class: "task--#{t.status}"}
        = link_to t.name, project_task_path(t.project, t)
.included-dependencies{'data-count': task.included_dependencies.count}
  %ul
    - task.included_dependencies.each do |t|
      %li.incomplete-prereq{class: "task--#{t.status}"}
        = link_to t.name, project_task_path(t.project, t)
        = t.complete? ? '(completed)' : ''

app/views/tasks/_parent_task_group.html.haml
- if task.parent
  = render 'tasks/parent_task_group', task: task.parent
  >
= link_to project_task_path(task.project, task) do
  = render 'tasks/iconed_task', task: task

app/views/tasks/_show.html.haml
.container.task{id: "task-#{@task.id}"}
  .project--info
    .row
      .col-md-12
        %h3= link_to @project.name, @project
        %h6= link_to "All Tasks", all_tasks_project_path(@project)
  .task--info
    .row
      .col-md-8
        %h2.task{class: "task--#{@task.status}"}
          = render 'iconed_task', task: @task, large: true
        - if @task.included? 
          = render 'task_checkbox', task: @task, label: (@task.complete? ? "Completed!" : "Mark Complete")
        - if @task.excluded? && @task.includable?
          %div{id: "task-#{@task.id}-form-wrap"}
            = render 'include_task_checkbox', task: @task, label: "Add to project"
          
      .col-md-4
        %ul.download-links
          - if @task.has_template?
            %li
              = link_to @task.template_url, target: "_NEW" do
                %img.icon{src: icon_path("User_Interface", "open_in_window")}
                Open Google Doc Template
              
      
  .task--extras
    .row
      - if  @task.prereq_tasks.any? || @task.parent
        .col-md-6
          - if @task.parent
            Task Group:
            = render 'tasks/parent_task_group', task: @task.parent
      
        .col-md-6
          Relies on:
          - if @task.prereq_tasks.any?
            - @task.prereq_tasks.each do |pre_task|
              %span.task{class: "task--#{pre_task.status}"}
                = link_to project_task_path(pre_task.project, pre_task) do
                  = render 'tasks/iconed_task', task: pre_task
          - else
            none
  .task--description
    .row
      .col-sm-12
        %p= @task.description
      
  - if @task.children.any?
    .task--tasks
      .row
        .col-xs-12
          .task-list
            %ul
              - @task.children.each do |sub_task|
                = render 'task', task: sub_task    

app/views/tasks/_task.html.haml
- skip_children ||= false
%li{class: "task task--#{task.status} #{task.children.any? ? 'task--group' : 'task--single'}", id: "task-#{task.id}"}
  = render 'tasks/task_checkbox', task: task
  = link_to project_task_path(task.project, task) do
    = render 'tasks/iconed_task', task: task
  - if task.completable?
    &nbsp;
    %span{id: "task-#{task.id}-include", class: 'task-action-link task-link--exclude'}
      = link_to 'remove', exclude_project_task_path(task.project, task, parent_task: @task), remote: true, onclick: render('tasks/change_completion_script', task: task, action: 'exclude')
      = render 'tasks/incomplete_prereqs', task: task
      
  -elsif task.includable?
    &nbsp;
    %span{id: "task-#{task.id}-include", class: 'task-action-link task-link--include'}
      = link_to '+add', include_project_task_path(task.project, task, parent_task: @task), remote: true, onclick: render('tasks/change_completion_script', task: task, action: 'include') 
      = render 'tasks/incomplete_prereqs', task: task
      
  - if !skip_children && task.children.any?
    .task-list
      %ul
        - task.children.each do |sub_task|
          = render sub_task
    
  :javascript
    $("#task-#{task.id} .task-action-link a").on("ajax:before", function() {
      SingleSteps.showWait();
    });    
          

app/views/tasks/_task_checkbox.html.haml
- label = label || nil
- if task.completable?
  = form_for [task.project, task], :html=>{class: "task__checkbox #{label ? 'task__checkbox--labeled' : ''}"}, remote: true, :authenticity_token => true do |f|
    = hidden_field_tag :parent_task, @task.id
    = render 'tasks/incomplete_prereqs', task: task
    = f.check_box "task_#{task.id}_complete?", onclick: render('tasks/change_completion_script', task: task, action: (task.complete? ? 'inprogress' : 'complete')), checked: task.complete?
    - if label
      = f.label "task_#{task.id}_complete?", label
- else
  %span.task__checkbox--sub

app/views/tasks/all_tasks.js.erb
$("#project-<%= @project.id %>").replaceWith("<%= j (render 'projects/all_tasks') %>");
SingleSteps.hideWait();

app/views/tasks/include_task_checkbox.js.erb
$("li#task-<%= @task.id %>").replaceWith("<%= j (render 'include_task', task: @task) %>");
SingleSteps.hideWait();

app/views/tasks/show.html.haml
= render 'show'

app/views/tasks/task_checkbox.js.erb
$("#task-<%= @task.id %>").replaceWith("<%= j (render 'show') %>");
SingleSteps.hideWait();