config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users
  resources :users
  namespace :admin do 
    resources :projects, only: :index
  end
  
  resources :projects do
    resources :tasks do
      member do
        get :include
        get :exclude        
      end
    end
    collection do
      get :find
    end
    member do
      get :select_tasks
      get :all_tasks
      get :unassign_user
    end
  end
  
end

app/models/project.rb
require 'tasks_parser'
require 'task_definition'
class Project < ApplicationRecord
  # Remove extra whitespace so find-by-name-and-pin can be cleaner
  extend FriendlyId
  friendly_id :id_and_name, use: :slugged
  def id_and_name
    "#{id} #{name}"
  end

  after_commit :update_slug, on: :create

  before_validation :clean_name, :clean_pin
  after_create :init_tasks
  
  has_many :tasks, dependent: :destroy
  has_and_belongs_to_many :users
  
  
  validates :name, uniqueness: { case_sensitive: false}
  validates_presence_of :name, :pin, :email
  
  
  def self.find_by_name_and_pin(name, pin)
    self.where(pin: pin.to_s.strip.upcase).where("lower(name) = ?", name.to_s.strip.downcase).first
  end
  
  
  def init_tasks!
    init_tasks
  end
  
  def status
    if excluded?
      'excluded'
    elsif complete?
      'complete'
    else
      'inprogress'
    end
  end
  
  def children
    tasks.roots
  end
  
  def complete?
    if children.any?
      children.all? {|c| c.complete? || c.excluded? }
    else
      super
    end
  end
  
  def excluded?
    if children.any?
      children.all?(&:excluded?)
    else
      super
    end
  end
  
  
  private
  def clean_name
    self.name = self.name.to_s.strip
  end
  def clean_pin
    self.pin = self.pin.to_s.strip.upcase
  end
  
  def init_tasks
    tasks.delete_all
    task_groups = TasksParser.parse_tasks
    task_groups.each do |key, task_def|
      t = add_task(task_def)
    end
  end
  
  def populate_prereqs
  end

  def add_task(task_def)
    t = Task.new(task_def.model_attributes)
    self.tasks << t
    t.save
    (task_def.tasks || {}).each do |key, sub_task_def|
      sub_task = add_task(sub_task_def)
      sub_task.parent_id = t.id
      sub_task.save
    end
    return t
  end

  def update_slug
    unless slug.include? self.id.to_s
      self.slug = nil
      self.save
    end
  end
  
  
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
  
  
  def index
    authorize :admin_page, :show?
  
    @projects = Project.all
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :unassign_user, :select_tasks, :all_tasks]
  # GET /projects
  # GET /projects.json
  def index
    if current_user
      @projects = current_user.projects
    else
      @projects = []
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def find
    name = params[:name]
    pin = params[:pin]
    @project = Project.find_by_name_and_pin(name, pin)
    if @project
      flash[:notice] = "Found project #{name}"
      if current_user
        current_user.add_project(@project)
      end
      redirect_to project_path(@project)
    else
      flash[:error] = "Could not find project '#{name}' with pin '#{pin}'"
      redirect_to projects_path
    end
  end
  
  def show
    raise ActionController::RoutingError.new('Project Not Found') if @project.nil?
    @tasks = @project.tasks.roots
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end
  
  def select_tasks
    @tasks = @project.tasks.roots
  end
  
  def all_tasks
    @task = @project #override the concept of the "parent" task for nested groups
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        if current_user
          current_user.add_project(@project)
        end
        format.html { redirect_to all_tasks_project_path(@project), notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def unassign_user
    if current_user
      current_user.remove_project(@project)
    end
    redirect_to projects_path
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find_by_slug(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :pin, :email)
    end
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_all_tasks.html.haml
.container{id: "project-#{@project.id}"}
  .row
    .col-xs-12
      %h2 
        All Tasks for
        = link_to @project.name, @project
      = link_to "https://drive.google.com/drive/u/0/folders/0Bx9xWWOdodAlUW45dnkwSjBFejA", target: "_NEW" do
        Open Folder of All Google Doc Templates
        %img.icon{src: icon_path("User_Interface", "open_in_window")}
  .row
    .col-xs-12
      .task-list
        %ul
          - @project.children.each do |task|      
            = render 'tasks/task', task: task

app/views/projects/_form.html.haml
= bootstrap_form_for @project do |f|
  - if @project.errors.any?
    #error_explanation
      %h2= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg
  = f.text_field :name, required: true
  = f.text_field :pin, required: true
  = f.text_field :email, label: "Project Team Contact Email Address", required: true, type: :email
  = f.submit 'Save'

app/views/projects/all_tasks.html.haml
= render 'projects/all_tasks'

app/views/projects/edit.html.haml
%h1 Editing project

= render 'form'

= link_to 'Show', @project
\|
= link_to 'Back', projects_path

app/views/projects/index.html.haml
.container
  .row
    .col-md-6
      %h3
        = link_to 'Create a new Project', new_project_path

    .col-md-6
      .row
        .col-xs-12
          %h3 Find a Project
      .row
        = bootstrap_form_tag url: find_projects_path, method: 'get' do |f|
          .col-md-6.col-lg-5
            = f.text_field :name
          .col-md-6.col-lg-5
            = f.text_field :pin
          .col-xs-12.col-lg-2
            .form-group
              .hidden-md-down
                %label.control-label 
                  &nbsp;
              = f.submit "Find"



- if @projects.any?
  %h1 Your projects

  %table.table.table-striped
    %thead
      %tr
        %th Name
        %th Pin
        %th
        %th
        %th

    %tbody
      - @projects.each do |project|
        %tr
          %td= project.name
          %td= project.pin
          %td= link_to 'Show', project
          %td= link_to 'Edit', edit_project_path(project)
          %td= link_to 'Remove', unassign_user_project_path(project), :data => { :confirm => 'Are you sure?' }

  %br

app/views/projects/new.html.haml
%h1 New project

= render 'form'

= link_to 'Back', projects_path

app/views/projects/select_tasks.html.haml
.container
  .row
    .col-xs-12
      %h2 
        Select Tasks for 
        = link_to @project.name, @project
  .row
    .col-xs-12
      .task-list
        %ul
          - @tasks.each do |task|      
            = render 'tasks/include_task', task: task

app/views/projects/show.html.haml
.container.project
  .row.project--info
    .col-md-6
      %h2= @project.name
      .project-detail
        %strong Pin:
        = @project.pin
      .project-detail
        %strong Project Team Contact Email:
        = @project.email
    .col-md-6
      = link_to 'Edit', edit_project_path(@project)
      
  .row
    .col-sm-6
      %h3 Activity Checklist
      %ul.activity-checklist
        - @tasks.each do |t|
          - if t.excluded?
            %li{class: "task--#{t.status}"}
              .checkbox="\u2612"
              %strong= t.name
              excluded
          - else
            %li{class: "task--#{t.download_status} task-group-#{t.id}--downloaded"}
              = form_for [t.project, t] do |f|
                .checkbox{onclick: "$(this).parent().submit()"}
                  = t.download_status=='complete' ? "\u2611" : "\u2610"
                  = f.hidden_field :download_complete, value: !t.download_complete?
                  = f.hidden_field :download_location, value: t.download_complete? ? '' : t.download_location
              = form_for [t.project, t] do |f|
                Modifiable spreadsheets for this project created.
                - if t.download_location.blank?
                  = f.label :download_location, "Enter Spreadsheet Location: "
                  = f.text_field :download_location
                  = f.hidden_field :download_complete, value: true
                  = f.submit "Save"
                - else 
                  %strong
                    %a{href: t.download_location, target: "_NEW"} 
                      Go to Spreadsheets
                      %img.icon{src: icon_path("User_Interface", "open_in_window")}
                  = f.hidden_field :download_complete, value: false
                  = f.hidden_field :download_location, value: ""                  
                  = f.hidden_field :new_download_location, value: t.download_location
                  = f.submit "Remove Spreadsheet Location"
            %li{class: "task--#{t.status}"}
              .checkbox=t.complete? ? "\u2611" : "\u2610"
              %strong= t.name
              = "tasks #{t.status_label}"
    .col-sm-6
      .row
        .col-sm-6
          %h3 Task Groups
        .col-sm-6
          = link_to 'All Tasks', all_tasks_project_path(@project)
      .task-list#top-level-task-groups
        %ul
          - @tasks.each do |t|
            %li{class: "task task--#{t.status} task--group"}
              = link_to t.name, project_task_path(t.project, t)