config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users
  resources :users
  namespace :admin do 
    resources :projects, only: :index
  end
  
  resources :projects do
    resources :tasks do
      member do
        get :include
        get :exclude        
      end
    end
    collection do
      get :find
    end
    member do
      get :select_tasks
      get :all_tasks
      get :unassign_user
    end
  end
  
end

app/views/layouts/_google_analytics.html.erb
<!-- Google Analytics -->
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-3177855-4', 'auto');
ga('create', 'UA-67501679-7', 'auto');
ga('send', 'pageview');
</script>
<!-- End Google Analytics -->

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", :role  => "alert"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_modal_confirm.html.erb
<div id="modal-confirm" class="modal fade">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title"><%=t('task.modal_confirm.title')%></h4>
      </div>
      <div class="modal-body">
        <p>
          <span class='task-dependency'><span>
        </p>
        <div class="prereq-list"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary btn-cancel" data-dismiss="modal"><%=t('task.modal_confirm.cancel')%></button>
        <button type="button" class="btn btn-primary btn-submit"><%=t('task.modal_confirm.continue')%></button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_modal_wait.html.erb
<div id="modal-wait" class="modal fade">
  <div class="modal-dialog" role="document">
    <div class="modal-spinner">&nbsp;</div>
  </div>
</div>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li class='nav-item'><%= link_to 'Admin', admin_projects_path, class: 'nav-link' %></li>
  <% end %>
  <li class='nav-item'><%= link_to 'Edit account', edit_user_registration_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete', class: 'nav-link' %>
<% elsif false %>
  <li class='nav-item'><%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %></li>
<% end %>

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
.container
  %nav.navbar.navbar-dark.bg-inverse
    %ul.nav.navbar-nav.clearfix
      %li.nav-item
        %button.navbar-toggler.hidden-sm-up.nav-link{"aria-controls" => "exCollapsingNavbar2", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#exCollapsingNavbar2", "data-toggle" => "collapse", :type => "button"}
          \ &#9776;
    #exCollapsingNavbar2.collapse.navbar-toggleable-xs
      = link_to "Single Steps", root_path, class: 'navbar-brand'
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'
        = render 'layouts/nav_links_for_auth'

app/views/layouts/_navigation_links.html.erb
<li class='nav-item'><%= link_to 'Projects', projects_path, class: 'nav-link' %></li>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Single Steps'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Single Steps'}"}
    = stylesheet_link_tag 'application', media: 'all'#, 'data-turbolinks-track' => reload
    = javascript_include_tag 'application'#, 'data-turbolinks-track' => reload
    = csrf_meta_tags
    = render 'layouts/google_analytics'
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield
      = render 'layouts/modal_wait'
      = render 'layouts/modal_confirm'
    %footer#footer
      %p
        Developed by 
        = link_to "Stephanie Singer", "https://www.linkedin.com/in/stephanie-singer-68499a"
        with funding from the 
        = link_to "Knight Foundation.", "http://www.knightfoundation.org/" 
        = link_to "Printable version", "http://campaignscientific.com/data/uploads/dataqualityguideforgovernments.pdf"
        available. 
        Icons by 
        = link_to "icons8.com.", "https://icons8.com/"
      %p.feedback
        = link_to "Your feedback", "http://bit.ly/SingleStepsFeedback"
        helps improve this app for everyone.